services:
    backend:
        environment:
            - NODE_ENV=development
        volumes:
            - './backend/src:/usr/src/app/src'
        command: npm run dev

    frontend:
        build:
            context: ./frontend
            dockerfile: Dockerfile.dev
        environment:
            - NODE_ENV=development
            - NEXT_PUBLIC_API_URL=http://localhost:5004
            - INTERNAL_API_URL=http://backend:5004

        volumes:
            - './frontend/src:/usr/src/app/src'
        command: npm run dev
        ports:
            - '5005:5005'
